List<String> countries =[
"ABW - Aruba", "AFG - Afghanistan", "AGO - Angola", "AIA - Anguilla", "ALA - Aland Islands", "ALB - Albania", "AND - Andorra", "ARE - United Arab Emirates",
"ARG - Argentina", "ARM - Armenia", "ASM - American Samoa", "ATA - Antarctica", "ATF - French Southern and Antarctic Lands", "ATG - Antigua and Barbuda", "AUS - Australia", "AUT - Austria", "AZE - Azerbaijan", "BDI - Burundi", "BEL - Belgium",
"BEN - Benin", "BFA - Burkina Faso", "BGD - Bangladesh", "BGR - Bulgaria", "BHR - Bahrain", "BHS - Bahamas", "BIH - Bosnia and Herzegovina", "BLM - Saint-Barthelemy", "BLR - Belarus",
"BLZ - Belize", "BMU - Bermuda", "BOL - Bolivia", "BRA - Brazil", "BRB - Barbados", "BRN - Brunei Darussalam", "BTN - Bhutan", "BWA - Botswana", "CAF - Central African Republic",
"CAN - Canada", "CHE - Switzerland", "CHL - Chile", "CHN - China", "CIV - Cote d'Ivoire", "CMR - Cameroon", "COD - Democratic Republic of the Congo", "COG - Republic of Congo", "COK - Cook Islands", "COL - Colombia", "COM - Comoros", "CPV - Cape Verde", "CRI - Costa Rica", "CUB - Cuba", "CUW - Curacao",
"CYM - Cayman Islands", "CYP - Cyprus", "CZE - Czech Republic", "DEU - Germany", "DJI - Djibouti", "DMA - Dominica", "DNK - Denmark", "DOM - Dominican Republic", "DZA - Algeria",
"ECU - Ecuador", "EGY - Egypt", "ERI - Eritrea", "ESP - Spain", "EST - Estonia", "ETH - Ethiopia",
"FIN - Finland", "FJI - Fiji", "FLK - Falkland Islands", "FRA - France", "FRO - Faeroe Islands", "FSM - Federated States of Micronesia", "GAB - Gabon", "GBR - United Kingdom", "GEO - Georgia", "GGY - Guernsey", "GHA - Ghana",
"GIB - Gibraltar", "GIN - Guinea", "GLP - Guadeloupe", "GMB - The Gambia", "GNB - Guinea-Bissau", "GNQ - Equatorial Guinea", "GRC - Greece", "GRD - Grenada", "GRL - Greenland", "GTM - Guatemala", "GUF - French Guiana", "GUM - Guam", "GUY - Guyana", "HKG - Hong Kong", "HMD - Heard I. and McDonald Islands", "HND - Honduras", "HRV - Croatia", "HTI - Haiti", "HUN - Hungary", "IDN - Indonesia",
"IMN - Isle of Man", "IND - India", "IOT - British Indian Ocean Territory", "IRL - Ireland", "IRN - Iran",
"IRQ - Iraq", "ISL - Iceland", "ISR - Palestine", "ITA - Italy", "JAM - Jamaica", "JEY - Jersey",
"JOR - Jordan", "JPN - Japan", "KAZ - Kazakhstan", "KEN - Kenya", "KGZ - Kyrgyzstan", "KHM - Cambodia", "KIR - Kiribati", "KNA - Saint Kitts and Nevis", "KOR - Republic of Korea", "KOS - Kosovo",
"KWT - Kuwait", "LAO - Lao PDR", "LBN - Lebanon", "LBR - Liberia", "LBY - Libya", "LCA - Saint Lucia", "LIE - Liechtenstein", "LKA - Sri Lanka",
"LSO - Lesotho", "LTU - Lithuania", "LUX - Luxembourg", "LVA - Latvia", "MAC - Macao", "MAF - Saint-Martin", "MAR - Morocco", "MCO - Monaco", "MDA - Moldova", "MDG - Madagascar", "MDV - Maldives", "MEX - Mexico", "MHL - Marshall Islands", "MKD - Macedonia, Former Yugoslav Republic of", "MLI - Mali", "MLT - Malta", "MMR - Myanmar", "MNE - Montenegro", "MNG - Mongolia", "MNP - Northern Mariana Islands", "MOZ - Mozambique", "MRT - Mauritania", "MSR - Montserrat", "MTQ - Martinique", "MUS - Mauritius", "MWI - Malawi", "MYS - Malaysia", "MYT - Mayotte", "NAM - Namibia", "NCL - New Caledonia", "NER - Niger", "NFK - Norfolk Island", "NGA - Nigeria", "NIC - Nicaragua", "NIU - Niue", "NLD - Netherlands", "NOR - Norway", "NPL - Nepal", "NRU - Nauru", "NZL - New Zealand", "OMN - Oman", "PAK - Pakistan", "PAN - Panama", "PCN - Pitcairn Islands", "PER - Peru", "PHL - Philippines", "PLW - Palau", "PNG - Papua New Guinea", "POL - Poland", "PRI - Puerto Rico", "PRK - Dem. Rep. Korea", "PRT - Portugal", "PRY - Paraguay", "PSE - Palestine", "PYF - French Polynesia", "QAT - Qatar", "REU - Reunion", "ROU - Romania", "RUS - Russian Federation", "RWA - Rwanda", "SAU - Saudi Arabia", "SDN - Sudan", "SEN - Senegal", "SGP - Singapore", "SGS - South Georgia and South Sandwich Islands"
];